version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - APP_PORT=8080
      - JAVA_OPTS=-Xmx512m
    ports:
      - "8080:8080"
    user: "appuser"
    volumes:
      - app_data:/data
volumes:
  app_data: